$ErrorActionPreference = 'Stop'
Set-Location (Resolve-Path (Join-Path $PSScriptRoot '..'))
function Assert-True([bool]$c,[string]$m){if(-not $c){throw $m}}
function Assert-Contains([string]$t,[string]$e,[string]$c){Assert-True $t.Contains($e) "$c is missing: $e"}
function Section([string]$t,[string]$s){$i=$t.IndexOf($s);Assert-True($i -ge 0) "Missing $s";$j=$t.IndexOf("`n    },",$i);Assert-True($j -gt $i) $s;return $t.Substring($i,$j-$i)}
$sp=(Get-Content include/constants/species.h -Raw)-replace "`r`n","`n";$dx=(Get-Content include/constants/pokedex.h -Raw)-replace "`r`n","`n";$inf=Get-Content src/data/pokemon/species_info.h -Raw;$gr=Get-Content src/data/graphics/pokemon.h -Raw;$egg=Get-Content src/data/pokemon/egg_moves.h -Raw;$learn=Get-Content src/data/pokemon/all_learnables.json -Raw|ConvertFrom-Json;$wild=Get-Content src/data/wild_encounters.json -Raw
Assert-Contains $sp "SPECIES_LENGHELIS,`n    SPECIES_LUSCINCO,`n    SPECIES_LUSCERP,`n    SPECIES_CUSTOM_END," 'Species order';Assert-Contains $dx "NATIONAL_DEX_LENGHELIS,`n    NATIONAL_DEX_LUSCINCO,`n    NATIONAL_DEX_LUSCERP," 'Dex order';Assert-Contains $dx '#define NATIONAL_DEX_COUNT  NATIONAL_DEX_LUSCERP' 'Dex count'
$expected=@{LUSCINCO=@('.baseHP = 45','.baseAttack = 60','.baseDefense = 45','.baseSpeed = 70','.baseSpAttack = 35','.baseSpDefense = 45','.types = MON_TYPES(TYPE_GRASS)','.catchRate = 190','.expYield = 64','.evYield_Speed = 1','.abilities = { ABILITY_CHLOROPHYLL, ABILITY_SHED_SKIN, ABILITY_REGENERATOR }','.natDexNum = NATIONAL_DEX_LUSCINCO','.categoryName = _("LUSCENGOLA")','.height = 4','.weight = 48','.frontAnimId = ANIM_H_SLIDE','.backAnimId = BACK_ANIM_H_SLIDE','FOOTPRINT(Treecko)','sPicTable_Treecko','.evolutions = EVOLUTION({EVO_LEVEL, 24, SPECIES_LUSCERP})');LUSCERP=@('.baseHP = 70','.baseAttack = 105','.baseDefense = 75','.baseSpeed = 100','.baseSpAttack = 55','.baseSpDefense = 75','.types = MON_TYPES(TYPE_GRASS, TYPE_DRAGON)','.catchRate = 75','.expYield = 175','.evYield_Attack = 2','.abilities = { ABILITY_CHLOROPHYLL, ABILITY_SHED_SKIN, ABILITY_REGENERATOR }','.natDexNum = NATIONAL_DEX_LUSCERP','.categoryName = _("SAURO")','.height = 15','.weight = 280','FOOTPRINT(Sceptile)','sPicTable_Sceptile')}
foreach($n in $expected.Keys){$r=Section $inf "[SPECIES_$n] =";foreach($e in $expected[$n]){Assert-Contains $r $e $n};Assert-True($r -notmatch 'ANIM_NONE|BACK_ANIM_NONE') "$n has invalid animation";foreach($a in 'anim_front.png','back.png','icon.png','normal.pal','shiny.pal'){Assert-True(Test-Path "graphics/pokemon/$($n.ToLower())/$a") "Missing $n asset $a"}}
foreach($m in 'MOVE_LEECH_SEED','MOVE_DRAGON_BREATH','MOVE_GRASSY_TERRAIN','MOVE_SYNTHESIS','MOVE_CURSE','MOVE_SCALE_SHOT'){Assert-Contains $egg $m 'Egg Moves'};foreach($n in 'LUSCINCO','LUSCERP'){Assert-True($null -ne $learn.$n) "$n teachables missing"};Assert-True($wild -notmatch 'LUSCINCO|LUSCERP') 'Line must not be in encounters';Assert-True((Get-ChildItem graphics/pokemon/luscinco -File).Count -eq 5) 'Luscinco asset count';Assert-True((Get-ChildItem graphics/pokemon/luscerp -File).Count -eq 5) 'Luscerp asset count';Write-Host 'Luscinco/Luscerp validation passed.' -ForegroundColor Green
