$ErrorActionPreference = 'Stop'
Set-Location (Resolve-Path (Join-Path $PSScriptRoot '..'))
function Assert-True([bool]$c,[string]$m){if(-not $c){throw $m}}
function Section([string]$t,[string]$s){$a=$t.IndexOf($s);Assert-True ($a -ge 0) "Missing $s";$b=$t.IndexOf("`n    },",$a);Assert-True ($b -gt $a) "Unterminated $s";$t.Substring($a,$b-$a)}
$sp=(Get-Content include/constants/species.h -Raw)-replace "`r`n","`n";$dex=(Get-Content include/constants/pokedex.h -Raw)-replace "`r`n","`n";$info=(Get-Content src/data/pokemon/species_info.h -Raw)-replace "`r`n","`n";$egg=(Get-Content src/data/pokemon/egg_moves.h -Raw)-replace "`r`n","`n";$wild=Get-Content src/data/wild_encounters.json -Raw;$learn=Get-Content src/data/pokemon/all_learnables.json -Raw|ConvertFrom-Json
Assert-True $sp.Contains("SPECIES_LUSCERP,`n    SPECIES_LUMELLA,`n    SPECIES_OMPHALUX,`n    SPECIES_PALUDIX,`n    SPECIES_SANGUILEX,`n    SPECIES_TRITINO,`n    SPECIES_TRICREST,`n    SPECIES_SALAMPOLLA,`n    SPECIES_ALCHIMANDRA,`n    SPECIES_CISTERNIDE,`n    SPECIES_CALCISTERN,`n    SPECIES_CUSTOM_END,") 'Species order/count mismatch';Assert-True $dex.Contains('#define NATIONAL_DEX_COUNT  NATIONAL_DEX_CALCISTERN') 'National Dex count mismatch'
$checks=@{PALUDIX=@('.types = MON_TYPES(TYPE_BUG, TYPE_WATER)','.baseHP = 45','.baseAttack = 35','.baseDefense = 45','.baseSpeed = 65','.baseSpAttack = 55','.baseSpDefense = 50','.catchRate = 200','.expYield = 58','.evYield_Speed = 1','.abilities = { ABILITY_SWIFT_SWIM, ABILITY_HYDRATION, ABILITY_RAIN_DISH }','.natDexNum = NATIONAL_DEX_PALUDIX','FOOTPRINT(Surskit)','sPicTable_Surskit','.frontAnimId = ANIM_V_SQUISH_AND_BOUNCE','.backAnimId = BACK_ANIM_H_SLIDE','TIME_EVENING','TIME_NIGHT');SANGUILEX=@('.types = MON_TYPES(TYPE_BUG, TYPE_POISON)','.baseHP = 65','.baseAttack = 90','.baseDefense = 60','.baseSpeed = 120','.baseSpAttack = 70','.baseSpDefense = 65','.catchRate = 90','.expYield = 168','.evYield_Speed = 2','.abilities = { ABILITY_SWARM, ABILITY_INFILTRATOR, ABILITY_POISON_TOUCH }','.natDexNum = NATIONAL_DEX_SANGUILEX','FOOTPRINT(Masquerain)','sPicTable_Masquerain','.cryId = CRY_VENOMOTH','.frontAnimId = ANIM_CIRCLE_C_CLOCKWISE_LONG','.backAnimId = BACK_ANIM_H_SLIDE')}
foreach($n in $checks.Keys){$r=Section $info "[SPECIES_$n] =";foreach($x in $checks[$n]){Assert-True $r.Contains($x) "$n missing $x"}}
Assert-True $egg.Contains('sPaludixEggMoveLearnset') 'Paludix Egg Moves missing';Assert-True $egg.Contains('#define sSanguilexEggMoveLearnset sPaludixEggMoveLearnset') 'Sanguilex Egg Moves missing'
foreach($n in 'PALUDIX','SANGUILEX'){Assert-True ($null -ne $learn.$n) "$n teachables missing";Assert-True (@($learn.$n).Count -eq 24) "$n teachable count mismatch"}
Assert-True (-not ($wild -match 'SANGUILEX')) 'Sanguilex must not be in encounters';foreach($n in 'paludix','sanguilex'){$p="graphics/pokemon/$n";Assert-True ((Get-ChildItem $p -File).Count -eq 5) "$n must have exactly five assets";Assert-True (-not (Get-ChildItem $p -File|Where-Object {$_.Name -match 'zip|preview|concept'})) "$n contains forbidden asset"}
Write-Host 'Paludix/Sanguilex validation passed.' -ForegroundColor Green
