param([string]$RepositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path)
$ErrorActionPreference = 'Stop'
function J($p){Get-Content (Join-Path $RepositoryRoot $p) -Raw | ConvertFrom-Json}
function A([bool]$c,[string]$m){if(-not $c){throw $m}}
$names=@('LagoDiAlbera_RefugeMastersHouse_1F','LagoDiAlbera_RefugeMastersHouse_2F','LagoDiAlbera_BikeShop','LagoDiAlbera_RefugeShop')
foreach($n in $names){$m=J "data/maps/$n/map.json"; A ($m.id -like 'MAP_LAGO_DI_ALBERA_*') "$n identity"; A (Test-Path (Join-Path $RepositoryRoot "data/layouts/$n/map.bin")) "$n map.bin missing"; A (@($m.coord_events).Count -eq 0) "$n unexpected coord events"}
$m1=J 'data/maps/LagoDiAlbera_RefugeMastersHouse_1F/map.json'; $m2=J 'data/maps/LagoDiAlbera_RefugeMastersHouse_2F/map.json'; A (@($m1.bg_events).Count -eq 1 -and @($m2.bg_events).Count -eq 2) 'Example/register events missing'
$l=J 'data/maps/LagoDiAlbera/map.json'; A (@($l.warp_events).Count -eq 5) 'External warp count'; A (@($l.warp_events | ? { $_.x -eq 6 -and $_.y -eq 109 -and $_.dest_map -eq 'MAP_LAGO_DI_ALBERA_REFUGE_MASTERS_HOUSE_1F' }).Count -eq 1) 'Masters House warp'; A (@($l.warp_events | ? { $_.x -eq 113 -and $_.y -eq 67 -and $_.dest_map -eq 'MAP_LAGO_DI_ALBERA_BIKE_SHOP' }).Count -eq 1) 'Bike Shop warp'; A (@($l.warp_events | ? { $_.x -eq 111 -and $_.y -eq 108 -and $_.dest_map -eq 'MAP_LAGO_DI_ALBERA_REFUGE_SHOP' }).Count -eq 1) 'Refuge Shop warp'; A (@($l.warp_events | ? { $_.x -eq 71 -and $_.y -eq 72 -and $_.dest_map -eq 'MAP_LAGO_DI_ALBERA_WATER_GYM_1F' }).Count -eq 1) 'Water Gym warp'; A (@($l.warp_events | ? { $_.x -eq 81 -and $_.y -eq 3 -and $_.elevation -eq 3 -and $_.dest_map -eq 'MAP_EMISSARIO' -and $_.dest_warp_id -eq '0' }).Count -eq 1) 'Emissario warp'; A (@($l.bg_events | ? type -eq 'secret_base').Count -eq 2) 'Secret Base events'; A ((@($l.object_events|? local_id -eq 'LOCALID_LAGO_DI_ALBERA_BAGNANTE')[0].graphics_id -eq 'OBJ_EVENT_GFX_SWIMMER_F') -and ((@($l.object_events|? local_id -eq 'LOCALID_LAGO_DI_ALBERA_BAGNANTE')[0].elevation) -eq 1)) 'Bagnante configuration'
$f=Get-Content (Join-Path $RepositoryRoot 'include/constants/flags.h') -Raw; foreach($x in 'FLAG_LAGO_REFUGE_MASTER_EXPLAINED_STONE_BASES','FLAG_LAGO_REFUGE_FIRST_MISSION_STARTED','FLAG_LAGO_REFUGE_AMULET_COIN_RECEIVED','FLAG_RECEIVED_LAGO_BIKE'){A ($f.Contains($x)) "Missing $x"}
$s=Get-Content (Join-Path $RepositoryRoot 'src/secret_base.c') -Raw; A ($s -match 'Special_GetPlayerSecretBaseId' -and $s -match 'secretBases\[0\]\.secretBaseId' -and $s -match 'gSpecialVar_Result') 'Special missing'
$shop=Get-Content (Join-Path $RepositoryRoot 'data/maps/LagoDiAlbera_RefugeShop/scripts.inc') -Raw; foreach($x in 'DECOR_CAMP_CHAIR','DECOR_CAMP_DESK','DECOR_HARD_CHAIR','DECOR_COMFORT_CHAIR','DECOR_GLITTER_MAT','DECOR_SPIN_MAT','DECOR_PRETTY_FLOWERS','DECOR_RED_PLANT'){A ($shop.Contains($x)) "Missing decoration $x"}
Write-Output 'Lago di Albera civic interiors validation passed.'
