gText_Birch_Welcome::
	.string "Ciao! Scusa se ti ho fatto aspettare!\p"
	.string "Benvenuto nel mondo di POKéMON ALBA!\p"
	.string "Mi chiamo LAURO.\p"
	.string "Ma tutti mi chiamano PROFESSORE\n"
	.string "POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Questa creatura si chiama POKéMON.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Il nostro mondo è popolato da\n"
	.string "creature chiamate POKéMON.\p"
	.string "Noi umani viviamo con i POKéMON:\n"
	.string "a volte come amici, altre\l"
	.string "come compagni di lavoro.\p"
	.string "A volte lottiamo al loro fianco\n"
	.string "contro altri Allenatori.\p"
	.string "Nonostante questo legame, sappiamo\n"
	.string "ancora poco dei POKéMON.\p"
	.string "Molti dei loro segreti devono\n"
	.string "ancora essere scoperti.\p"
	.string "Per svelarli, porto avanti\n"
	.string "le mie ricerche.\l"
	.string "Questo è il mio lavoro.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "E tu chi sei?$"

gText_Birch_BoyOrGirl::
	.string "Sei un ragazzo?\n"
	.string "Oppure sei una ragazza?$"

gText_Birch_WhatsYourName::
	.string "Bene.\n"
	.string "Come ti chiami?$"

gText_Birch_SoItsPlayer::
	.string "Ah, quindi ti chiami\n{PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, va bene!\p"
	.string "Tu sei {PLAYER}{KUN}, vero?\n"
	.string "Ti stai trasferendo ad ALBÈRA.\l"
	.string "Ora ricordo!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Bene, ci siamo?\p"
	.string "La tua avventura sta per\n"
	.string "cominciare.\p"
	.string "Fatti coraggio ed entra nel\n"
	.string "mondo dei POKéMON, dove sogni,\l"
	.string "avventure e amicizie ti aspettano!\p"
	.string "Bene, ti aspetterò più tardi.\n"
	.string "Vieni al LABORATORIO DEL CRATERE.\p"
	.string "$"
