gText_Birch_Welcome::
	.string "Ciao! Scusa se ti ho fatto aspettare!\p"
	.string "Benvenuto nel mondo di POKéMON ALBA!\p"
	.string "Mi chiamo BIRCH.\p"
	.string "Ma tutti mi chiamano PROFESSORE\n"
	.string "POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Questa creatura si chiama POKéMON.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Il nostro mondo è popolato da\n"
	.string "creature chiamate POKéMON.\p"
	.string "Noi umani viviamo con i POKéMON:\n"
	.string "a volte come amici, altre\l"
	.string "come compagni di lavoro.\p"
	.string "A volte lottiamo al loro fianco\n"
	.string "contro altri Allenatori.\p"
	.string "Nonostante questo legame, sappiamo\n"
	.string "ancora poco dei POKéMON.\p"
	.string "Molti dei loro segreti devono\n"
	.string "ancora essere scoperti.\p"
	.string "Per svelarli, porto avanti\n"
	.string "le mie ricerche.\l"
	.string "Questo è il mio lavoro.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "E tu chi sei?$"

gText_Birch_BoyOrGirl::
	.string "Sei un ragazzo?\n"
	.string "Oppure sei una ragazza?$"

gText_Birch_WhatsYourName::
	.string "Bene.\n"
	.string "Come ti chiami?$"

gText_Birch_SoItsPlayer::
	.string "Ah, quindi ti chiami\n{PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
