	.align 2
gText_ConfirmSave::
	.string "Vuoi salvare la partita?$"

gText_AlreadySavedFile::
	.string "Esiste già un salvataggio.\n"
	.string "Vuoi sovrascriverlo?$"

gText_SavingDontTurnOff::
	.string "SALVATAGGIO IN CORSO…\n"
	.string "NON SPEGNERE.$"

gText_PlayerSavedGame::
	.string "{PLAYER} ha salvato\n"
	.string "la partita.$"

gText_DifferentSaveFile::
	.string "ATTENZIONE!\p"
	.string "È già salvata una partita diversa.\p"
	.string "Salvando ora, l'altra avventura,\n"
	.string "inclusi strumenti e POKéMON,\l"
	.string "andrà completamente persa.\p"
	.string "Vuoi salvare e sovrascrivere\n"
	.string "l'altra partita?$"

gText_SaveError::
	.string "Errore di salvataggio.\p"
	.string "Sostituisci la memoria\n"
	.string "di backup.$"

gText_SavingDontTurnOffPower::
	.string "SALVATAGGIO IN CORSO…\n"
	.string "NON SPEGNERE.$"
