OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Quando inizia una lotta, il primo\n"
	.string "POKéMON della squadra scende in campo.\p"
	.string "Se ne hai più di uno, prova a cambiare\n"
	.string "l'ordine della squadra.\p"
	.string "Potresti ottenere un vantaggio.$"
