gText_HowMayIServeYou::
	.string "Benvenuto!\p"
	.string "Come posso servirti?$"

gText_PleaseComeAgain::
	.string "Grazie! Torna a trovarci!$"

gText_PlayerWhatCanIDoForYou::
	.string "{PLAYER}{KUN}, benvenuto!\p"
	.string "Cosa posso fare per te?$"

Pokemart_DefaultItemList::
	.2byte ITEM_ULTRA_BALL
	.2byte ITEM_HYPER_POTION
	.2byte ITEM_MAX_POTION
	.2byte ITEM_FULL_RESTORE
	.2byte ITEM_FULL_HEAL
	.2byte ITEM_REVIVE
	.2byte ITEM_MAX_REPEL
	pokemartlistend
