BorgoDiCastello_MapScripts::
	.byte 0

BorgoDiCastello_EventScript_VillaPapaleSign::
	msgbox BorgoDiCastello_Text_VillaPapaleSign, MSGBOX_SIGN
	end

BorgoDiCastello_Text_VillaPapaleSign:
	.string "Villa Papale\n"
	.string "{UP_ARROW} A nord$"

BorgoDiCastello_EventScript_AnzianoBelvedere::
	msgbox BorgoDiCastello_Text_AnzianoBelvedere, MSGBOX_NPC
	end

BorgoDiCastello_EventScript_TuristaBelvedere::
	msgbox BorgoDiCastello_Text_TuristaBelvedere, MSGBOX_NPC
	end

BorgoDiCastello_EventScript_ResidenteVicoli::
	msgbox BorgoDiCastello_Text_ResidenteVicoli, MSGBOX_NPC
	end

BorgoDiCastello_EventScript_ViaggiatoreLaricia::
	msgbox BorgoDiCastello_Text_ViaggiatoreLaricia, MSGBOX_NPC
	end

BorgoDiCastello_EventScript_Bambino::
	msgbox BorgoDiCastello_Text_Bambino, MSGBOX_NPC
	end

BorgoDiCastello_EventScript_DonnaVilla::
	msgbox BorgoDiCastello_Text_DonnaVilla, MSGBOX_NPC
	end

BorgoDiCastello_EventScript_ViaggiatorePiazza::
	msgbox BorgoDiCastello_Text_ViaggiatorePiazza, MSGBOX_NPC
	end

BorgoDiCastello_EventScript_AbitanteFontana::
	msgbox BorgoDiCastello_Text_AbitanteFontana, MSGBOX_NPC
	end

BorgoDiCastello_Text_AnzianoBelvedere:
	.string "Da quassu il LAGO DI ALBERA\n"
	.string "sembra sempre lo stesso.\p"
	.string "Ma chi vive qui da tanto\n"
	.string "sa che non e proprio cosi.$"

BorgoDiCastello_Text_TuristaBelvedere:
	.string "Che vista!\p"
	.string "Capisco perche questo posto\n"
	.string "attiri gente da ogni parte.$"

BorgoDiCastello_Text_ResidenteVicoli:
	.string "Ultimamente si vedono\n"
	.string "parecchi forestieri.\p"
	.string "Pare che alcuni siano molto\n"
	.string "interessati alla Villa Papale.$"

BorgoDiCastello_Text_ViaggiatoreLaricia:
	.string "Verso est la strada scende\n"
	.string "in direzione di Laricia.\p"
	.string "Piu avanti il paesaggio\n"
	.string "cambia completamente.$"

BorgoDiCastello_Text_Bambino:
	.string "Ogni tanto vedo dei POKEMON\n"
	.string "saltare sui tetti!\p"
	.string "Sono troppo veloci per me!$"

BorgoDiCastello_Text_DonnaVilla:
	.string "La Villa Papale conserva\n"
	.string "documenti molto antichi.\p"
	.string "Non tutto, pero, e accessibile\n"
	.string "ai visitatori.$"

BorgoDiCastello_Text_ViaggiatorePiazza:
	.string "Arrivo dalla zona di Laricia.\p"
	.string "La campagna laggiu e enorme.\n"
	.string "Campi a perdita d'occhio.$"

BorgoDiCastello_Text_AbitanteFontana:
	.string "La fontana e il punto\n"
	.string "d'incontro di tutto il borgo.\p"
	.string "Prima o poi qui passa sempre\n"
	.string "qualcuno che conosci.$"
