LagoDiAlbera_EastHouse2_MapScripts::
	.byte 0

LagoDiAlbera_EastHouse2_EventScript_Hiker::
	msgbox LagoDiAlbera_EastHouse2_Text_Hiker, MSGBOX_NPC
	end

LagoDiAlbera_EastHouse2_EventScript_BirdWatcher::
	msgbox LagoDiAlbera_EastHouse2_Text_BirdWatcher, MSGBOX_NPC
	end

LagoDiAlbera_EastHouse2_Text_Hiker:
	.string "Albera non ha bisogno di un grande fiume.\n"
	.string "Pioggia e sorgenti nascoste alimentano\n"
	.string "il lago da sempre.$"

LagoDiAlbera_EastHouse2_Text_BirdWatcher:
	.string "Guarda le pareti alte del cratere.\n"
	.string "I POKéMON alati scelgono posti dove noi\n"
	.string "faticheremmo perfino ad arrivare.$"
